version: "2"
services:
  hourai:
    build: .
    container_name: "hourai"
    command: python launcher.py run
    restart: unless-stopped
    environment:
      # Bot Configuration
      - BOT_TOKEN=""
      # Database Configuration
      - DB_CONNECTION=sqlite://
      - REDIS_CONNECTION=redis://hourai_redis_dev
      # Reddit Feed Configuration
      - REDDIT_CLIENT_ID=""
      - REDDIT_CLIENT_SECRET=""
      - REDDIT_USER_AGENT=""
      - REDDIT_USERNAME=""
      - REDDIT_PASSWORD=""
      - REDDIT_BASE_URL=https://reddit.com
      - REDDIT_FETCH_LIMIT=20
    depends_on:
      - main_database
      - redis_cache
  main_database:
    image: "postgres:11-alpine"
    container_name: "postgres"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hourai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  redis_cache:
    image: "redis:5.0-alpine"
    container_name: "redis"
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    mem_limit: 100m
volumes:
  db-data:
  redis-data:
