version: "2.3"
services:
  hourai:
    build: .
    container_name: "hourai-${HOURAI_ENV:-dev}"
    command: python launcher.py run
    restart: unless-stopped
    environment:
      - HOURAI_CONFIG=/opt/hourai.jsonnet
      - HOURAI_ENV=${HOURAI_ENV:-dev}
    volumes:
      - hourai-data:/data
      - ./config/hourai.jsonnet:/opt/hourai.jsonnet
    depends_on:
      - main_database
      - redis
      - lavalink
  main_database:
    image: "postgres:11-alpine"
    container_name: "postgres-{HOURAI_ENV-dev}"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hourai
      - POSTGRES_USER=hourai
      - POSTGRES_PASSWORD=password
  redis:
    image: "redis:5.0-alpine"
    container_name: "redis-${HOURAI_ENV:-dev}"
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    volumes:
      - redis-data:/data
    mem_limit: 100M
  lavalink:
    image: "fredboat/lavalink:master"
    restart: unless-stopped
    container_name: "lavalink-${HOURAI_ENV:-dev}"
    volumes:
      - ./config/lavalink.yml:/opt/Lavalink/application.yml
    expose:
      - 2333
volumes:
  hourai-data:
    name: "hourai-data-${HOURAI_ENV:-dev}"
  db-data:
    name: "db-data-${HOURAI_ENV:-dev}"
  redis-data:
    name: "redis-data-${HOURAI_ENV:-dev}"
