version: "2"
services:
  hourai:
    build: .
    container_name: "hourai"
    command: python launcher.py run
    restart: unless-stopped
    enviroment:
      - HOURAI_CONFIG=/opt/hourai.jsonnet
      - HOURAI_ENV=prod
    volumes:
      - ./config/hourai.jsonnet:/opt/hourai.jsonnet
    depends_on:
      - main_database
      - redis_cache
  main_database:
    image: "postgres:11-alpine"
    container_name: "postgres"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hourai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  redis_cache:
    image: "redis:5.0-alpine"
    container_name: "redis"
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    mem_limit: 100m
  lavalink:
    image: "fredboat/lavalink:master"
    volumes:
      - ./config/lavalink.yml:/opt/lavalink/application.yml
volumes:
  db-data:
  redis-data:
